### ISSUE TITLE
EntityAbstract `one` method

### ISSUE THREAD

**Issue by SvenAlHamad** [Webiny/Framework#25]
If would be useful to have  method `one` for picking the first result from the `find` query, instead of constantly doing find and then picking the first result.

```php
// this is the current solution
User::find(['name'=>'foo'])[0];

// this is the proposed solution
User::one(['name'=>'foo']);
```

**Comment by Pavel910** [comment]
`findOne($conditions)` is the implemented method name, to keep `find` methods grouped in autocomplete.
