### ISSUE TITLE
All Keys Exists on Array

### ISSUE THREAD

**Issue by adrian1358** [Webiny/Framework#36]
It would be nice to have a method that would check if all keys exists in given array. Usable for custom API calls, where developers could do initial checks of received data and throw exceptions if something is missing. 

Method could throw `true` if all keys are there, otherwise array of missing keys.

Example:

```php
        /**
         * Checks if all keys exist in given array
         * TODO: Possible upgrade: nested fields checks.
         *
         * @param $keys         Array All obligatory keys (string - keys separated by comma or array)
         * @param $array        Array Array to check
         *
         * @return array|bool   Array of missing keys or true if all keys exist
         */

        public function arrayKeysExist($keys, $array)
        {
            $missing = [];
            if (!is_array($keys)) {
                $keys = explode(',', $keys);
            }
            foreach ($keys as $key) {
                if (!array_key_exists($key, $array)) {
                    $missing[] = $key;
                }
            }
            return empty($missing) ? true : $missing;
        }
`

**Comment by SvenAlHamad** [comment]
Did you try using the array diff method?

https://github.com/Webiny/Framework/blob/master/src/Webiny/Component/StdLib/StdObject/ArrayObject/ManipulatorTrait.php#L1027

http://php.net/manual/en/function.array-diff.php

**Comment by adrian1358** [comment]
No I didn't try that, but I see now this can also get the job done, thanks!
