### ISSUE TITLE
Router appendRoutes() error

### ISSUE THREAD

**Issue by Pavel910** [Webiny/Framework#37]
```
Fatal error: Call to a member function add() on a non-object in /var/www/webiny/src/Webiny/Component/Router/Router.php on line 226
```

This happens if you don't call Router::setConfig(). Setting router config should not be mandatory. I very often append routes to Router myself, and settings 1 config is not possible due to loading different modules each of which have its own config.

The problem is in this method inside Router.php:

```php
public function appendRoutes(ConfigObject $routes)
    {
        foreach ($routes as $name => $routeConfig) {
            self::$_routeCollection->add($name, $this->_loader->processRoute($routeConfig));
        }

        return $this;
    }
```

self::$_routeCollection is not initialized if Router::setConfig() is not called, causing this error to be thrown.

**Comment by SvenAlHamad** [comment]
Solved with the latest release, the Router has an initialize() method that can be called, when you are not defining your methods using a config file.
