### ISSUE TITLE
Crypt.php Microaudit

### ISSUE THREAD

**Issue by defuse** [Webiny/Framework#39]
Time-boxing an audit of [Crypt.php](https://github.com/Webiny/Framework/blob/master/src/Webiny/Component/Crypt/Bridge/Webiny/Crypt.php) limited to 20 minutes: 

1. In `_generator`: There is absolutely no use to combining `mt_rand()` and `microtime()` with `mcrypt_create_iv()`. In fact, every extra step you do is only increasing the likelyhood of mistakes causing the result to be less random. Just use `mcrypt_create_iv()` and nothing more. Keep it simple.

2. What I hypothesized in (1) did indeed happen. First, a specific problem: The call to `hash()` for `$seedThree` returns the hash as a *hex*, not in binary. So `$seedThree` will take on only hex character values (0-9a-f), so some of the output is going to be hex characters, and not random bytes. A more general problem: The bytes generated by the other techniques have very low entropy. That means in the output there are likely to be low entropy bytes. Because of the shuffle, (which is also low entropy) an attacker may not know where those bytes are, but  that doesn't matter because they are still there. Again, just use `mcrypt_create_iv()`.

3. There is no padding applied to the plaintext before encryption. That means you'll get extra null bytes in the plaintext after decryption (`mcrypt_encrypt` pads with nulls).

4. The IV is not included in the hash. An attacker could modify what the plaintext decrypts to by changing the IV (this breaks confidentiality as well, in some cases).

5. The `decrypt()` function doesn't properly validate the ciphertext format. Most of the calls to `substr()` just assume the string has the correct length, when it might not.

6. The way it derives `$mackey` from `$key` is not standard, it should be doing HKDF.

7. In `generateRandomString()`: The line `$o = ord($random[$i]) % $len;` introduces heavy bias into the output because of the `%` unless `$len` divides 256 (it doesn't).

8. In `generateRandomInt()`, it takes the `strlen()` of an integer `$range`, which makes no sense to me. That's not the right way to do it. [Here](https://github.com/defuse/php-passgen/blob/master/PasswordGenerator.php) is an example of how to do it correctly.

9. In `generateRandomInt()`, well... the whole process makes no sense and is probably very biased. See the above link for the correct algorithm for doing this.

Conclusion: This code is very broken and I recommend scrapping it. Replace it with:

For encryption: https://github.com/defuse/php-encryption/
For password generating: https://github.com/defuse/php-passgen/blob/master/PasswordGenerator.php

Both of the above libraries are very carefully written, and I suggest at least studying them to learn more about how hard it is to do this right. **Please do not write your own crypto.**

**Comment by SvenAlHamad** [comment]
Hi Taylor, 

thank you for responding to our review request, we much appreciate your feedback.

We did look at the libraries you wrote, and we were interested in integrating them, instead of rolling our own, but unfortunately those libraries are not available on composer, which make is impossible for us to use them, and also licensing of those components is not specified. If the components get those updates, we will definitely be interested in integrating them.

For the time being we will take into account your feedback and correct the noted issues. 

I do thank you again, we really appreciate when somebody is willing to step up and give honest and concrete feedback.

**Comment by defuse** [comment]
@SvenAlHamad I will prioritize getting those libraries on composer so that they are more easy to use. Crypto.php is under the MIT license, and I will apply the MIT license to the password generating one as well.

**Comment by defuse** [comment]
Crypto.php is now in composer.

**Comment by defuse** [comment]
php-encryption: https://packagist.org/packages/defuse/php-encryption
php-passgen: https://packagist.org/packages/defuse/php-passgen

**Comment by SvenAlHamad** [comment]
@defuse Thank you for getting the libraries to composer, I did manage to install them. 

Looking at the library there are still some issues that prevent us from using the library:
php-encryption:
1. exception handler is globally overwritten 
2. key needs to have 16 bytes - not sure why is that, why don't you internally hash the given key to the requested length and use that for encryption, that way the key can be of any length
3. missing namespaces

php-passgen:
1. PasswordGenerator.php has a closing php tag, that can cause a lot of issues when returning output to browser
2. doesn't support generating random int between min and max int

I see that some of them are already reported on your repo. I believe once those issues are resolved, a lot members will be looking at the library, including us, but for the time being that is preventing us from using them. 

I've added myself to the watchlist, and will keep an eye on the progress. 

I do thank you again on your effort and contribution.

**Comment by defuse** [comment]
@SvenAlHamad Regarding the key size, it only accepts 16 byte keys because that is what AES accepts. If the user is passing in an alphanumeric string of variable length they are almost certainly using the library wrong. It is possible to accept a string of any length, but then it would be called a passphrase and there would be an additional step of key stretching to create the 16 byte key from it (this is a planned feature for Crypto.php).

**Comment by defuse** [comment]
I removed the closing tag from PasswordGenerator.php and added an (untested!) random int function. Will probably get around to addressing the other issues in the next few weeks. Thanks for the feedback!

**Comment by defuse** [comment]
@SvenAlHamad What do you think about this API for supporting passphrases (keys that are not random 16 bytes): https://github.com/defuse/php-encryption/issues/5#issuecomment-34369429 The reason an API like that is necessary is because the KDF function needs a random salt.

I strongly recommend just sticking to random 16-byte keys, though.

**Comment by SvenAlHamad** [comment]
I get that 16-byte keys are better, when it comes to the 'code-level', but it makes the public api less usable and developer friendly. The key should be making the library easy to use, without compromising the security aspect of the component itself. 

The proposed `KeyLocker` class should probably solve that problem.

For now, I've resolved the issues that you mentioned in your audit report, until your libraries are ready.

**Comment by SvenAlHamad** [comment]
Closing for now ... until the php-encryption and passgen tasks have been resolved.
