### ISSUE TITLE
REST warnings when sending sort as array

### ISSUE THREAD

**Issue by adrian1358** [Webiny/Framework#48]
Tried sending this:

![image](https://cloud.githubusercontent.com/assets/5121148/9311357/ff82a33e-4515-11e5-9bce-13fac1e90a8f.png)

And got this:

![image](https://cloud.githubusercontent.com/assets/5121148/9311394/2366c71c-4516-11e5-8dc2-1afee302cd69.png)

**Comment by adrian1358** [comment]
BTW one question, is it possible to put more than one sort key? Let's say I want to sort by name and then email... didn't see that in the official docs.. Tnx!

**Comment by Pavel910** [comment]
You can now do it by passing a comma-separated string: `_sort=+order,-createdOn`
