### ISSUE TITLE
Sorry to ask. How do u split framework repo.

### ISSUE THREAD

**Issue by collizo4sky** [Webiny/Framework#50]
How do you guys split the main framework components into read only repositories.

Would love to know. 

CC @SvenAlHamad @adrian1358

**Comment by SvenAlHamad** [comment]
Hey Collins,

this not really an issue :) but let me try and provide you some quick guidelines:
1. have a master repo, in our case (https://github.com/Webiny/Framework)
2. you only write and commit into master
3. check the composer json inside the master repo, especially the "replace" section which references the components. This tells to composer to resolve that dependency to the master repo.
4. creating and maintaining the component repos is bit time consuming, so we created this tool to automate that (https://github.com/Webiny/GitSplit)

Hope it helps.
